const jCategory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "Web Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Google",
    location: "Mountain View, California",
    vacancy: "03",
    hours: "40h / week",
    description:
      "Join Google's frontend engineering team to build responsive, accessible, and high-performance web applications used by millions of users worldwide.",
    workplace: "Hybrid",
    education: "Bachelor's degree in Computer Science or related field.",
    experience: "2+ years",
  },

  {
    index: 1,
    image: "../images/uber.png",
    title: "Freelancer",
    rate: "$900-1200/m",
    av: "Freelancer",
    companyName: "Uber",
    location: "San Francisco, California",
    vacancy: "05",
    hours: "Flexible",
    description:
      "Work on freelance web development projects, collaborate with international clients, and deliver scalable solutions within deadlines.",
    workplace: "Remote",
    education: "Diploma or Bachelor's degree.",
    experience: "1+ year",
  },

  {
    index: 2,
    image: "../images/linkedin.png",
    title: "Business Associate",
    rate: "$900-1200/m",
    av: "Part Time",
    companyName: "LinkedIn",
    location: "Bengaluru, India",
    vacancy: "08",
    hours: "45h / week",
    description:
      "Support business growth by managing client relationships, preparing reports, and identifying new partnership opportunities.",
    workplace: "Office",
    education: "Bachelor's degree in Business Administration.",
    experience: "1-3 years",
  },

  {
    index: 3,
    image: "../images/facebook.png",
    title: "Digital Marketing",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Meta",
    location: "Menlo Park, California",
    vacancy: "04",
    hours: "40h / week",
    description:
      "Create and optimize digital marketing campaigns, analyze campaign performance, and improve customer engagement across platforms.",
    workplace: "Hybrid",
    education: "Bachelor's degree in Marketing or related field.",
    experience: "2-4 years",
  },

  {
    index: 4,
    image: "../images/yahoo.png",
    title: "UI/UX Designer",
    rate: "$950-1300/m",
    av: "Full Time",
    companyName: "Yahoo",
    location: "New York, USA",
    vacancy: "02",
    hours: "38h / week",
    description:
      "Design modern user interfaces, create wireframes and prototypes, and collaborate closely with developers to improve user experience.",
    workplace: "Remote",
    education: "Bachelor's degree in Design or IT.",
    experience: "2 years",
  },

  {
    index: 5,
    image: "../images/apple.png",
    title: "Frontend Developer",
    rate: "$1200-1800/m",
    av: "Full Time",
    companyName: "Apple",
    location: "Cupertino, California",
    vacancy: "06",
    hours: "40h / week",
    description:
      "Develop beautiful and responsive frontend applications using modern JavaScript frameworks while maintaining excellent performance.",
    workplace: "On-site",
    education: "Bachelor's degree in Computer Science.",
    experience: "3+ years",
  },

  {
    index: 6,
    image: "../images/instagram.png",
    title: "Social Media Manager",
    rate: "$1000-1500/m",
    av: "Full Time",
    companyName: "Instagram",
    location: "London, United Kingdom",
    vacancy: "04",
    hours: "40h / week",
    description:
      "Plan content strategies, manage brand campaigns, monitor analytics, and increase audience engagement through creative social media content.",
    workplace: "Hybrid",
    education: "Bachelor's degree in Mass Communication or Marketing.",
    experience: "2-5 years",
  },

  {
    index: 7,
    image: "../images/wordpress.png",
    title: "WordPress Developer",
    rate: "$850-1400/m",
    av: "Remote",
    companyName: "WordPress",
    location: "Remote",
    vacancy: "07",
    hours: "35h / week",
    description:
      "Develop custom WordPress themes and plugins, optimize website performance, and maintain secure, SEO-friendly websites.",
    workplace: "Work from Home",
    education: "Bachelor's degree or equivalent experience.",
    experience: "1-3 years",
  },
];